# Generated by Django 5.2 on 2025-05-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_free', models.BooleanField(default=True)),
                ('background_class', models.CharField(help_text='ej: bg-white or bg-gradient-to-r from-purple-400 to-pink-500', max_length=200)),
                ('text_class', models.CharField(help_text='ej: text-gray-900 or text-white', max_length=200)),
                ('button_class', models.CharField(help_text='ej: bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
