# Generated by Django 5.2 on 2025-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('neon', 'Neón')], default='light', max_length=20),
        ),
    ]
