# Generated by Django 5.2 on 2025-05-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_profile_image_profile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('neon', 'Neón'), ('custom', 'Personalizado')], default='light', max_length=20),
        ),
    ]
