# Generated by Django 5.2 on 2025-05-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_color',
            field=models.CharField(default='#2563EB', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
