# Generated by Django 5.2 on 2025-05-14 20:38

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_enable_animations_profile_show_invite_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('font_family', models.CharField(choices=[('sans', 'Sans (por defecto)'), ('serif', 'Serif'), ('mono', 'Monoespaciada'), ('inter', 'Inter'), ('poppins', 'Poppins'), ('raleway', 'Raleway')], default='sans', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='theme_backgrounds/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.upload_avatar_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
